In this we are going to Understand How we Build Training Pipeline in PyTorch.

1. Load the dataset
2. Basic preprocessing (Scaling, Encoding)
3. Training Process
  - Create the model
  - Forward pass
  - Loss calculation
  - Backprop
  - Parameters update (using Gradient Descent)
4. Model evaluation using (Accuracy)


In [77]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [78]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [79]:
df.shape

(569, 33)

## **PreProcessing**

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [81]:
# Drop Unnecessary columns
df.drop(columns=['id','Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [82]:
df.shape

(569, 31)

**Train Test Split**

Here our first column is target column.

In [83]:
x_train, x_test, y_train , y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size=0.2)

Now Most of Our Values in Multiple Columns are not in a standard form. That means Every Columns has its own range of values highs and lows and not all values are in a uniform scale. This will be tough for comparision. Thus we have to make them into some standard unit.

In [84]:
# Scaling
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [85]:
x_train

array([[ 0.98535128, -1.01334579,  0.95370903, ...,  0.47844102,
        -0.2444311 , -0.26447551],
       [-1.55822987, -1.15483545, -1.55556094, ..., -1.77041686,
        -0.49894806, -0.30284979],
       [-0.56097685, -0.31061384, -0.56684727, ..., -0.89157062,
        -0.78760754, -0.36716726],
       ...,
       [-0.40091331, -0.39550764, -0.45542541, ..., -1.21252712,
        -1.16162332, -1.28815012],
       [-0.4523623 , -0.71385936, -0.44424181, ..., -0.47129986,
         0.37479004, -0.47039949],
       [-0.27229082, -0.16204971, -0.24832158, ...,  1.45459361,
         1.53097989,  1.82773381]])

In [86]:
x_test

array([[-0.74427793, -0.1995998 , -0.73982616, ..., -0.85824898,
        -1.29234385, -0.43630432],
       [-1.2234007 , -0.82501251, -1.13523689, ...,  0.61451672,
         0.519675  ,  2.64275168],
       [-0.49487914, -0.11532433, -0.52136274, ..., -0.43479816,
         0.26800571, -0.71797079],
       ...,
       [ 0.53319807,  0.13084876,  0.4899375 , ...,  0.54088566,
        -0.40244126, -1.21415146],
       [-0.35632426, -1.27300317, -0.36779343, ...,  0.01391822,
        -0.94202021,  0.13262465],
       [ 1.94368676,  0.88267468,  1.82409603, ...,  1.24687765,
        -0.05614433, -0.50594371]])

**Now our Y has 2 categories i.e Not Numbers. Thus we have to encode it into Numbers and we will do this using Label Encoder.Because it has 2 categories so Binary Classification Problem**

In [87]:
y_train

29     M
175    B
480    B
178    B
281    B
      ..
524    B
364    B
429    B
502    B
47     M
Name: diagnosis, Length: 455, dtype: object

In [88]:
y_test

304    B
152    B
107    B
174    B
475    B
      ..
16     M
362    B
75     M
322    B
23     M
Name: diagnosis, Length: 114, dtype: object

In [89]:
# Encode it to Numbers

encoder = LabelEncoder()

y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [90]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,

**Convert the np.array to Tensors**

In [91]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [92]:
x_train_tensor

tensor([[ 0.9854, -1.0133,  0.9537,  ...,  0.4784, -0.2444, -0.2645],
        [-1.5582, -1.1548, -1.5556,  ..., -1.7704, -0.4989, -0.3028],
        [-0.5610, -0.3106, -0.5668,  ..., -0.8916, -0.7876, -0.3672],
        ...,
        [-0.4009, -0.3955, -0.4554,  ..., -1.2125, -1.1616, -1.2882],
        [-0.4524, -0.7139, -0.4442,  ..., -0.4713,  0.3748, -0.4704],
        [-0.2723, -0.1620, -0.2483,  ...,  1.4546,  1.5310,  1.8277]],
       dtype=torch.float64)

In [93]:
x_train_tensor.shape

torch.Size([455, 30])

## **Model Building(Define the Model)**

In [94]:
"""
Decide the Structure
"""
class MySimpleNetwork():

  # constructor function getting data
  def __init__(self, X):
    """
    We have 30 input features thus we will need 30 weights for that.
    So making a matrix of 30x1.
    We need to update weights and perform all derivates on weights and bias thus we make grad=True.
    """

    self.weights = torch.rand(X.shape[1], 1 , dtype=torch.float64, requires_grad=True)

    # we are making one neuron only thus one neuron with its bias as 0 in start
    self.bias = torch.zeros(1 , dtype=torch.float64, requires_grad=True)


  # Forward Pass
  def forward_pass(self,X):

    # Calculate z
    z = torch.matmul(X,self.weights) + self.bias

    # predict y with activation on z
    y_pred = torch.sigmoid(z)

    return y_pred

  # Loss Function
  def loss_function(self, y_pred, y):
    """
    Since we are doing binary classification.
    We decide to choose Binary Cross Entropy as a Loss Function.
    """
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss(Formula Based)
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()

    return loss

**Important Parameter**

In [95]:
# We need to define the learning rates which are usefull for optimization.
learning_rate = 0.1

# How many runs/loops on data
epochs = 25

## **Training Pipeline**

**Create Model**

In [96]:
# creating model
model = MySimpleNetwork(x_train_tensor)

In [97]:
# check attributes
model.weights
model.weights.shape

torch.Size([30, 1])

In [98]:
model.bias
model.bias.shape

torch.Size([1])

**PipeLine**

In Loop

  - forward pass (The calculation of z = w*x+b => activation function on z)
  - loss calculate
  - backward pass
  - parameter update

In [99]:
for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward_pass(x_train_tensor)

  # Loss Calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # BackWard Loss(backPropogate)
  loss.backward()

  # Update the weights (without derivative tracking)
  # w_new = w_old - (learning_rate * dL/dw) ==> formula
  # b_new = b_old - (learning_rate * dL/db) ==> formula
  with torch.no_grad():
    """
    We dont want to calculate gradient in this operations.
    We need to update the weights and based on new derivate we will be changing weights so this operation does not required gradient tracking.
    """
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Clear the gradients for future updates of weights
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # Print the Loss
  print(f"Epoch:{epoch +1}, Loss:{loss}")
  print('='*60)


Epoch:1, Loss:3.538762026682595
Epoch:2, Loss:3.407826563295666
Epoch:3, Loss:3.2708535718787637
Epoch:4, Loss:3.1290528730592397
Epoch:5, Loss:2.9876393863240236
Epoch:6, Loss:2.846037289354933
Epoch:7, Loss:2.696049997006928
Epoch:8, Loss:2.5406369196998084
Epoch:9, Loss:2.3882067548635906
Epoch:10, Loss:2.236202427681073
Epoch:11, Loss:2.086191533165283
Epoch:12, Loss:1.934315474978228
Epoch:13, Loss:1.7836339329483175
Epoch:14, Loss:1.6421845963931891
Epoch:15, Loss:1.507918829398995
Epoch:16, Loss:1.3778799342118602
Epoch:17, Loss:1.2624899001050884
Epoch:18, Loss:1.1629200332999894
Epoch:19, Loss:1.0796410835439536
Epoch:20, Loss:1.0120641678554865
Epoch:21, Loss:0.9584902389626194
Epoch:22, Loss:0.9165164504689911
Epoch:23, Loss:0.883629395012038
Epoch:24, Loss:0.8576169786161644
Epoch:25, Loss:0.836717558597275


In [100]:
model.weights

tensor([[ 0.3079],
        [-0.0730],
        [ 0.5103],
        [ 0.2153],
        [-0.2817],
        [-0.3943],
        [-0.0247],
        [-0.5324],
        [ 0.2469],
        [ 0.3244],
        [ 0.3251],
        [ 0.2060],
        [-0.1407],
        [ 0.6116],
        [ 0.0220],
        [ 0.2679],
        [-0.1100],
        [ 0.3345],
        [ 0.2761],
        [ 0.0921],
        [-0.2012],
        [ 0.3003],
        [-0.3006],
        [-0.2176],
        [ 0.3042],
        [-0.2966],
        [ 0.1621],
        [-0.5463],
        [ 0.4178],
        [ 0.2144]], dtype=torch.float64, requires_grad=True)

In [101]:
model.bias

tensor([-0.1200], dtype=torch.float64, requires_grad=True)

## **Evaluation**

In [106]:
with torch.no_grad():
  y_pred = model.forward_pass(x_test_tensor)

print(y_pred)

tensor([[0.2608],
        [0.9965],
        [0.2541],
        [0.6197],
        [0.2201],
        [0.7243],
        [0.7736],
        [0.3382],
        [0.7217],
        [0.7114],
        [0.6009],
        [0.9583],
        [0.3720],
        [0.3052],
        [0.3060],
        [0.3783],
        [0.5684],
        [0.3944],
        [0.8620],
        [0.6435],
        [0.6468],
        [0.5130],
        [0.9139],
        [0.6864],
        [0.3990],
        [0.4572],
        [0.3839],
        [0.3184],
        [0.1213],
        [0.2567],
        [0.5820],
        [0.2544],
        [0.5221],
        [0.4807],
        [0.3217],
        [0.1794],
        [0.2210],
        [0.5006],
        [0.1302],
        [0.8205],
        [0.4430],
        [0.3053],
        [0.2008],
        [0.5247],
        [0.6858],
        [0.9907],
        [0.1864],
        [0.4539],
        [0.0937],
        [0.8174],
        [0.4711],
        [0.3940],
        [0.5177],
        [0.4501],
        [0.5650],
        [0

Now our Prediction is in numbers.

So How we are going to compare thos with the testing values? Because our Testing values are 0s and 1s.

So for such cases simply decide the threshold for predicted values to be 0 and 1.

In [108]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward_pass(x_test_tensor)

  # Convert values to 1
  y_pred = (y_pred > 0.9).float()

  # how many predictions are correct by comparing with Test
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')


Accuracy: 0.6386580467224121
