In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

## **PreProcessing**

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [5]:
# Drop Unnecessary columns
df.drop(columns=['id','Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
df.shape

(569, 31)

**Train Test Split**

Here our first column is target column.

In [7]:
x_train, x_test, y_train , y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size=0.2)

Now Most of Our Values in Multiple Columns are not in a standard form. That means Every Columns has its own range of values highs and lows and not all values are in a uniform scale. This will be tough for comparision. Thus we have to make them into some standard unit.

In [8]:
# Scaling
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [9]:
x_train

array([[-8.12429084e-01,  3.30533651e+00, -8.58797872e-01, ...,
        -1.27458832e+00,  2.62539114e-03, -6.10877463e-01],
       [-8.63449988e-01, -1.01999576e+00, -8.63719944e-01, ...,
        -7.06963511e-01,  4.51740266e-01, -6.21905750e-01],
       [-8.86125945e-01, -4.03727553e-01, -8.58797872e-01, ...,
        -2.36918123e-01, -9.57338363e-01, -7.54540907e-02],
       ...,
       [ 7.52211959e-01,  5.05783523e-01,  7.53590839e-01, ...,
         1.01406524e+00,  3.01524476e+00,  1.20298017e-01],
       [-4.12765340e-01,  3.15633852e-01, -3.92841735e-01, ...,
        -5.70391516e-02, -1.05456942e+00,  3.92401022e-02],
       [-5.00634674e-01, -1.60189958e+00, -5.28198711e-01, ...,
        -3.08022511e-01, -1.27016016e-01, -9.06435575e-01]])

In [10]:
x_train.dtype

dtype('float64')

In [11]:
x_test

array([[ 0.21754294,  0.03755406,  0.18149242, ..., -0.06173896,
        -1.21911027, -0.76998167],
       [-1.51697609, -1.13162907, -1.53408671, ..., -1.59636852,
         0.25927425, -0.28864999],
       [-0.54507204, -0.360519  , -0.51564511, ..., -0.28010028,
        -0.09937474,  1.62308619],
       ...,
       [-0.07775534, -0.81617495, -0.1402311 , ..., -0.52849409,
        -1.52354488, -0.90815218],
       [ 1.50768106,  2.46605007,  1.70579915, ...,  1.22246332,
        -0.10145991,  0.98319819],
       [ 1.19518094, -0.10014417,  1.18147791, ...,  0.75476967,
         1.72723292,  0.15021125]])

In [12]:
x_test.dtype

dtype('float64')

**Now our Y has 2 categories i.e Not Numbers. Thus we have to encode it into Numbers and we will do this using Label Encoder.Because it has 2 categories so Binary Classification Problem**

In [13]:
y_train

232    B
381    B
534    B
505    B
289    B
      ..
435    M
403    B
35     M
111    B
170    B
Name: diagnosis, Length: 455, dtype: object

In [14]:
y_test

514    M
307    B
383    B
27     M
354    B
      ..
2      M
453    B
439    B
256    M
85     M
Name: diagnosis, Length: 114, dtype: object

In [15]:
# Encode it to Numbers

encoder = LabelEncoder()

y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [16]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,

In [17]:
y_train.dtype

dtype('int64')

**Convert the np.array to Tensors**

In [18]:
x_train_tensor = torch.from_numpy(x_train.astype(np.float32))
x_test_tensor = torch.from_numpy(x_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [19]:
x_train_tensor

tensor([[-8.1243e-01,  3.3053e+00, -8.5880e-01,  ..., -1.2746e+00,
          2.6254e-03, -6.1088e-01],
        [-8.6345e-01, -1.0200e+00, -8.6372e-01,  ..., -7.0696e-01,
          4.5174e-01, -6.2191e-01],
        [-8.8613e-01, -4.0373e-01, -8.5880e-01,  ..., -2.3692e-01,
         -9.5734e-01, -7.5454e-02],
        ...,
        [ 7.5221e-01,  5.0578e-01,  7.5359e-01,  ...,  1.0141e+00,
          3.0152e+00,  1.2030e-01],
        [-4.1277e-01,  3.1563e-01, -3.9284e-01,  ..., -5.7039e-02,
         -1.0546e+00,  3.9240e-02],
        [-5.0063e-01, -1.6019e+00, -5.2820e-01,  ..., -3.0802e-01,
         -1.2702e-01, -9.0644e-01]])

In [20]:
x_train_tensor.shape

torch.Size([455, 30])

In [21]:
x_train_tensor.dtype

torch.float32

## **Custom DataSet Class**

In [22]:
from torch.utils.data import Dataset, DataLoader

In [23]:
# Dataset Class

class CustomDataSet(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    # return all rows
    return self.features.shape[0]

  def __getitem__(self, index):
    # return item at that index
    return self.features[index],self.labels[index]

In [24]:
# Create dataset from this class object
train_dataset = CustomDataSet(x_train_tensor, y_train_tensor)
test_dataset = CustomDataSet(x_test_tensor, y_test_tensor)

In [25]:
# Create Data Loader

# One for training
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# One for Testing
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

## **Create Model**

In [26]:
import torch.nn as nn

In [27]:
class MySimpleNetwork(nn.Module):

  # constructor function getting data
  def __init__(self, num_features):

    super().__init__()

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  # Forward Pass
  def forward(self,features):

    # Calculate z
    z = self.linear(features)
    y_pred = self.sigmoid(z)

    return y_pred

**Important Parameter**

In [28]:
# We need to define the learning rates which are usefull for optimization.
learning_rate = 0.1

# How many runs/loops on data
epochs = 25

In [29]:
# Loss Function
loss_function = nn.BCELoss()

In [32]:
x_train_tensor.shape

torch.Size([455, 30])

In [33]:
# creating model
model = MySimpleNetwork(x_train_tensor.shape[1])

In [34]:
# Optimizer Stocastic Gradient Descent
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

## **Training Pipeline**

Here we will have main changes.

- One Loop For Epochs
- One loop for Batches

In [36]:
for epoch in range(epochs):

  # Because our trainloader have features and labels
  for batch_features, batch_labels in train_loader:

    # Forward Pass
    y_pred = model.forward(batch_features)

    # Loss Calculate
    loss = loss_function(y_pred.squeeze(), batch_labels)

    # Make gradeints zero(Doing it before backward pass bcoz it is suggested.)
    optimizer.zero_grad()

    # BackWard Loss(backPropogate)
    loss.backward()

    # Update weight & bias using optimizer
    optimizer.step()

  # Print the Loss
  print(f"Epoch:{epoch +1}, Loss:{loss}")
  print('='*60)


Epoch:1, Loss:0.06464629620313644
Epoch:2, Loss:0.054707229137420654
Epoch:3, Loss:0.03497875854372978
Epoch:4, Loss:0.046189941465854645
Epoch:5, Loss:0.026039408519864082
Epoch:6, Loss:0.05910873040556908
Epoch:7, Loss:0.001776601537130773
Epoch:8, Loss:0.1394737809896469
Epoch:9, Loss:0.08148790895938873
Epoch:10, Loss:0.02242332696914673
Epoch:11, Loss:0.18534259498119354
Epoch:12, Loss:0.04353444650769234
Epoch:13, Loss:0.01831572689116001
Epoch:14, Loss:0.17919482290744781
Epoch:15, Loss:0.09417269378900528
Epoch:16, Loss:0.008532178588211536
Epoch:17, Loss:0.11718691140413284
Epoch:18, Loss:0.08053447306156158
Epoch:19, Loss:0.2925930619239807
Epoch:20, Loss:0.010904232040047646
Epoch:21, Loss:0.028238162398338318
Epoch:22, Loss:0.05317080020904541
Epoch:23, Loss:0.46309131383895874
Epoch:24, Loss:0.007720501162111759
Epoch:25, Loss:0.008472233079373837


In [37]:
model.linear.weight

Parameter containing:
tensor([[ 0.4617,  0.5339,  0.4551,  0.6094,  0.1077,  0.1551,  0.4338,  0.8143,
          0.1087, -0.4243,  0.9847,  0.1427,  0.6319,  0.5652, -0.1159, -0.5441,
         -0.1745, -0.0619, -0.1571, -0.5642,  0.8401,  0.8289,  0.7837,  0.7159,
          0.7051,  0.2971,  0.6961,  0.5839,  0.6348,  0.2521]],
       requires_grad=True)

In [38]:
model.linear.bias

Parameter containing:
tensor([-0.5248], requires_grad=True)

## **Evaluation**

In [39]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.squeeze() == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9470


In [41]:
len(accuracy_list)

4